In [2]:
import pandas as pd
import numpy as np
from numpy import savetxt

In [2]:
data = pd.read_csv('combined.csv')

In [3]:
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20
0,0.598581,0.728022,-4.155619,1.787265,-2.165891,-0.255073,-1.781371,0.935368,-0.571673,3.181152,-2.185762,-0.294838,1.002794,-0.959564,-2.431593,0.269351,0.408053,-0.485530,2.265961,-0.683756
1,-0.231030,-0.131568,-2.875510,1.241566,-0.312527,0.521358,-1.483054,1.162572,0.965199,2.166193,-2.980876,-0.468518,-1.263787,-0.608398,-2.322453,1.227273,-0.085586,0.809849,2.341795,-0.286909
2,1.179237,0.997716,-2.206613,1.619468,-1.465168,-0.125984,-1.314249,1.243039,0.118771,1.396744,-2.293225,-0.320680,1.582689,-0.772539,-2.186980,1.409452,0.753483,-0.727624,2.451872,-1.145823
3,-1.969814,0.844728,-2.129175,1.190092,-0.495035,-1.106257,1.769345,0.945406,0.434916,0.888209,-2.740821,0.252473,3.302833,-1.400573,2.151298,-2.100775,-0.455836,0.123596,-0.260301,-3.789165
4,0.013961,-0.210841,-3.253482,1.019738,-1.207102,-1.130372,-1.576202,0.876479,0.400829,2.974763,-3.115360,-0.364671,0.204171,-1.023645,-2.641203,0.346258,-1.405920,-0.124335,2.465128,-0.625163

In [4]:
data.dtypes

V1     float64
V2     float64
V3     float64
V4     float64
V5     float64
V6     float64
V7     float64
V8     float64
V9     float64
V10    float64
V11    float64
V12    float64
V13    float64
V14    float64
V15    float64
V16    float64
V17    float64
V18    float64
V19    float64
V20    float64
dtype: object

In [14]:
#np.ones(len(data))

In [5]:
#data.insert(0, 'new-col', np.ones(len(data)))

In [7]:
n = len(data)
data = np.array(data)

for i in range(len(data.T)):
    data[:,i] = (data[:,i]-min(data[:,i]))/(max(data[:,i])-min(data[:,i]))

data = np.concatenate((np.ones(n).reshape(-1,1), data), axis =1)
savetxt('combined.csv', data, delimiter=',')

In [8]:
np.savetxt("combined.csv", data, delimiter=",")

In [9]:
cm = pd.read_csv('true_CM.csv')

In [10]:
cm = np.array(cm)

In [11]:
np.savetxt("combined.csv", cm, delimiter=",")

In [12]:
cm.shape

(20, 20)

In [4]:
pd.read_csv('combined.csv', header = None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,1.0,0.866657,0.412435,0.414937,0.388747,0.282660,0.571213,0.376940,0.884704,0.238486,0.298933,0.748227,0.302422,0.236995,0.366969,0.323877,0.289549,0.204141
1,1.0,0.944239,0.333207,0.387439,0.439566,0.155234,0.561569,0.284925,0.885644,0.391374,0.315701,0.628198,0.473525,0.417223,0.292908,0.544465,0.188387,0.374945
2,1.0,0.841480,0.533355,0.536213,0.487674,0.375905,0.618177,0.481395,0.835999,0.442282,0.384454,0.813773,0.430348,0.404796,0.460436,0.468168,0.350382,0.345671
3,1.0,0.940376,0.692603,0.675809,0.615720,0.510661,0.812339,0.651024,0.956351,0.278231,0.257186,0.900724,0.449359,0.286446,0.646259,0.465039,0.544822,0.255807
4,1.0,0.854573,0.589046,0.617516,0.505861,0.472585,0.690172,0.563547,0.837126,0.269157,0.337902,0.619572,0.358138,0.256355,0.593371,0.404593,0.486051,0.267675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1.0,0.678683,0.151241,0.205812,0.176734,0.275181,0.394261,0.234608,0.624488,0.441617,0.148103,0.442967,0.140333,0.177245,0.234834,0.162990,0.303262,0.496508
4996,1.0,0.351158,0.367746,0.340444,0.311991,0.545013,0.305666,0.427430,0.302571,0.582490,0.336980,0.359027,0.346296,0.438427,0.419490,0.406832,0.532483,0.509057
4997,1.0,0.497023,0.362853,0.411083,0.311522,0.447761,0.348575,0.399374,0.496072,0.602102,0.283742,0.327324,0.203145,0.376485,0.400622,0.246195,0.443961,0.572288
4998,1.0,0.443775,0.077536,0.073204,0.086852,0.318391,0.143618,0.173385,0.435290,0.501653,0.294037,0.172885,0.191752,0.306452,0.167105,0.262647,0.336454,0.550199
4999,1.0,0.575420,0.341300,0.418354,0.299192,0.458159,0.494831,0.423428,0.530037,0.374010,0.173279,0.440055,0.192390,0.255867,0.425654,0.199122,0.434871,0.427996